const items = [
    { name: 'أذكار الاستيقاظ من النوم', title: 'Title 1', description: 'الحمـد لله الذي أحـيانا بعـد ما أماتـنا وإليه النـشور.' },
    { name: 'أذكار النوم', title: 'Title 2', description: 'Description 2' },
    { name: 'أذكار الصباح', title: 'Title 2', description: 'Description 2' },
    { name: 'أذكار المساء', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء الذهاب إلى المسجد', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء دخول المسجد', title: 'Title 2', description: 'Description 2' },
    { name: 'الدعاء بعد التشهد الأخير وقبل السلام', title: 'Title 2', description: 'Description 2' },
    { name: ' الأذكار بعد السلام من الصلاة', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء الخروج من المسجد', title: 'Title 2', description: 'Description 2' },
    { name: 'الدعاء عند إفطار الصائم', title: 'Title 2', description: 'Description 2' },
    { name: ' الدعاء إذا نزل المطر', title: 'Title 2', description: 'Description 2' },
    { name: ' الذكر بعد نزول المطر', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء الريح', title: 'Title 2', description: 'Description 2' },
    { name: ' دعاء الرعد', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء الغضب', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء الهم والحزن', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء الكرب', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء دخول السوق', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء السفر', title: 'Title 2', description: 'Description 2' },
    { name: 'ذكر الرجوع من السفر', title: 'Title 2', description: 'Description 2' },
    { name: 'الدعاء إذا تقلب ليلاً', title: 'Title 2', description: 'Description 2' },
    { name: 'ما يفعل من رأى الرؤيا أو الحلم', title: 'Title 2', description: 'Description 2' },
    { name: 'الذكر عقب السلام من الوتر', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء من أصيب بمصيبة', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء طرد الشيطان ووساوسه', title: 'Title 2', description: 'Description 2' },
    { name: 'الدعاء للميت في الصلاة عليه', title: 'Title 2', description: 'Description 2' },
    { name: ' الدعاء بعد دفن الميت', title: 'Title 2', description: 'Description 2' },
    { name: 'دعاء زيارة القبور', title: 'Title 2', description: 'Description 2' },
    // Add more items as needed
  ];